version: "3.3"
services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: repo/movies-backend:1
    working_dir: /opt/api/
    command: bash run.sh
    ports:
      - 5000:5000
    volumes:
      - ./api/:/opt/api/
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    depends_on:
      - mongo
    expose:
      - 5000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo:/data/db
  node:
    image: node:latest
    volumes:
      - ./frontend:/opt/frontend
    working_dir: /opt/frontend
  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: unless-stopped
